"""Added initial table

Revision ID: 914729691ddd
Revises: 
Create Date: 2024-08-09 20:29:58.968359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914729691ddd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walkers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walkers_id'), 'walkers', ['id'], unique=False)
    op.create_index(op.f('ix_walkers_second_name'), 'walkers', ['second_name'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_number', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(length=100), nullable=False),
    sa.Column('pet_breed', sa.String(length=100), nullable=False),
    sa.Column('walk_start', sa.DateTime(), nullable=False),
    sa.Column('walk_end', sa.DateTime(), nullable=False),
    sa.Column('walker_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['walker_id'], ['walkers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_walk_end'), 'orders', ['walk_end'], unique=False)
    op.create_index(op.f('ix_orders_walk_start'), 'orders', ['walk_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_walk_start'), table_name='orders')
    op.drop_index(op.f('ix_orders_walk_end'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_walkers_second_name'), table_name='walkers')
    op.drop_index(op.f('ix_walkers_id'), table_name='walkers')
    op.drop_table('walkers')
    # ### end Alembic commands ###
