"""change order tabl

Revision ID: ff57940d93e2
Revises: 479bbe803878
Create Date: 2024-08-09 20:46:42.772899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff57940d93e2'
down_revision: Union[str, None] = '479bbe803878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'walker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'walker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
